sonar.projectKey=persis-76-tarogong_smart-santri
sonar.organization=persis-76-tarogong

# Bypass Coverage and Duplication checks for Free Tier
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*

# Only scan the main application source code (ignore docs, scripts, etc.)
sonar.sources=src

# Exclude unnecessary files from being scanned
sonar.exclusions=**/*.test.*, **/*.spec.*