sonar.projectKey=persis-76-tarogong_smart-santri
sonar.organization=persis-76-tarogong

# Bypass Coverage and Duplication checks for Free Tier
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*

# Only scan the main application source code (ignore docs, scripts, etc.)
sonar.sources=src

# Exclude unnecessary files from being scanned
sonar.exclusions=**/*.test.*, **/*.spec.*

# Mengabaikan aturan Cognitive Complexity agar algoritma finansial tidak perlu dipecah
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S3776
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*